language: java
jdk:
  - oraclejdk8
before_install:
- "sudo rm -vf /etc/apt/sources.list.d/*riak*"
- "sudo apt-get -qq update"
- "sudo apt-get -qq install --no-install-recommends tree latexmk latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended latex-xcolor"
- "pip install --user mako click"
- "ant init-ivy"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install: ant resolve

script:
  - ./gradlew build
  - mkdir -p build/pages
  - ./gradlew javadoc
  - cp -r build/docs/* build/pages
  - mkdir -p build/pages/dist
  - cp build/libs/*.jar build/pages/dist
  - ./scripts/build.sh work_packages build/pages
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  local_dir: build/pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
