language: java
before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends tree latexmk latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended"
- "pip install --user mako click"
script:
  - ./gradlew javadoc
  - ./scripts/build.sh work_packages build/docs
deploy:
  provider: pages
  local_dir: build/docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master