/**
 * This Java source file was generated by the Gradle 'init' task.
 *
 * A simple class to demonstrate some JavaDoc, among other tools.
 * These tools could include:
 * <ol>
 * <li> Google's style guide. I think there's a tool to automatically enforce this.
 * <li> JUnit, the unit-testing framework for Java.
 * <li> Eventually, a Java build tool of some kind (Gradle, Maven, whatever).
 * <li> Travis CI, which is going to build everything, run our tests, 
 *      tell us if they fail, build the docs, and push them to a GitHub Pages site.
 * </ol>
 */

import wayside.WaysideControllerGUI;

public class App {
    /**
     * A basic function that can be tested with simple code.
     *
     * @return a friendly greeting string
     */
    public String getGreeting() {
        return "Hello world.";
    }

    /**
     * Here we have the all-important entry point into our application.
     *
     * @param args Command-line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaysideControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaysideControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaysideControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaysideControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaysideControllerGUI().setVisible(true);
            }
        });
    }
}
