/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainmodel;

import javax.swing.JOptionPane;
import javax.*;
import java.*;
import static java.lang.String.valueOf;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Parth
 */
public class TrainModelGUI extends javax.swing.JFrame {

    /**
     * Creates new form TrainModelGUI
     */
    public TrainModelGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        debugModeGroup = new javax.swing.ButtonGroup();
        emergencyBrakeGroup = new javax.swing.ButtonGroup();
        lightGroup = new javax.swing.ButtonGroup();
        leftDoorGroup = new javax.swing.ButtonGroup();
        rightDoorGroup = new javax.swing.ButtonGroup();
        brakesGroup = new javax.swing.ButtonGroup();
        engineGroup = new javax.swing.ButtonGroup();
        signalGroup = new javax.swing.ButtonGroup();
        passengersDisplayLabel = new javax.swing.JLabel();
        currentTrainSpeedDisplayLabel = new javax.swing.JLabel();
        massLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        emergencyBrakeLabel = new javax.swing.JLabel();
        temperatureDisplayLabel = new javax.swing.JLabel();
        accelerationDisplayLabel = new javax.swing.JLabel();
        emergencyBrakeDisplayLabel = new javax.swing.JLabel();
        leftDoorLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rightDoorLabel = new javax.swing.JLabel();
        accelerationLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        massDisplayLabel = new javax.swing.JLabel();
        passengersLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        crewLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        trainIdPicker = new javax.swing.JComboBox<>();
        lengthLabel = new javax.swing.JLabel();
        authorityDisplayLabel = new javax.swing.JLabel();
        numCarsLabel = new javax.swing.JLabel();
        powerDisplayLabel = new javax.swing.JLabel();
        heightDisplayLabel = new javax.swing.JLabel();
        lightsDisplayLabel = new javax.swing.JLabel();
        leftDoorDisplayLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        trainIdLabel = new javax.swing.JLabel();
        authorityLabel = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();
        currentTrainSpeedLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        widthDisplayLabel = new javax.swing.JLabel();
        lengthDisplayLabel = new javax.swing.JLabel();
        rightDoorDisplayLabel = new javax.swing.JLabel();
        numCarsDisplayLabel = new javax.swing.JLabel();
        crewDisplayLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        debugModeOnButton = new javax.swing.JRadioButton();
        debugModeOffButton = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        setAuthorityInput = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        emergencyBrakeOnButton = new javax.swing.JRadioButton();
        emergencyBrakeOffButton = new javax.swing.JRadioButton();
        jLabel43 = new javax.swing.JLabel();
        lightsOnButton = new javax.swing.JRadioButton();
        lightsOffButton = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        setPowerInput = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        leftDoorOpenButton = new javax.swing.JRadioButton();
        leftDoorCloseButton = new javax.swing.JRadioButton();
        rightDoorCloseButton = new javax.swing.JRadioButton();
        rightDoorOpenButton = new javax.swing.JRadioButton();
        jLabel48 = new javax.swing.JLabel();
        setTemperatureInput = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        brakeFailureOnButton = new javax.swing.JRadioButton();
        brakeFailureOffButton = new javax.swing.JRadioButton();
        enginFailureOnButton = new javax.swing.JRadioButton();
        engineFailureOffButton = new javax.swing.JRadioButton();
        signalFailureOnButton = new javax.swing.JRadioButton();
        signalFailureOffButton = new javax.swing.JRadioButton();
        applyChangesButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        setTimeInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        passengersDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        passengersDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        passengersDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengersDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        passengersDisplayLabel.setOpaque(true);

        currentTrainSpeedDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        currentTrainSpeedDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        currentTrainSpeedDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrainSpeedDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        currentTrainSpeedDisplayLabel.setOpaque(true);

        massLabel.setBackground(new java.awt.Color(153, 204, 255));
        massLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        massLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        massLabel.setText("Mass");
        massLabel.setOpaque(true);

        temperatureLabel.setBackground(new java.awt.Color(153, 204, 255));
        temperatureLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temperatureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureLabel.setText("Temperature");
        temperatureLabel.setOpaque(true);

        emergencyBrakeLabel.setBackground(new java.awt.Color(153, 204, 255));
        emergencyBrakeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emergencyBrakeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeLabel.setText("Emergency Brake");
        emergencyBrakeLabel.setOpaque(true);

        temperatureDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        temperatureDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        temperatureDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        temperatureDisplayLabel.setOpaque(true);

        accelerationDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        accelerationDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        accelerationDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accelerationDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        accelerationDisplayLabel.setOpaque(true);

        emergencyBrakeDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        emergencyBrakeDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emergencyBrakeDisplayLabel.setOpaque(true);

        leftDoorLabel.setBackground(new java.awt.Color(153, 204, 255));
        leftDoorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        leftDoorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorLabel.setText("Left");
        leftDoorLabel.setOpaque(true);

        jLabel30.setBackground(new java.awt.Color(213, 166, 189));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Dimensions");
        jLabel30.setOpaque(true);

        rightDoorLabel.setBackground(new java.awt.Color(153, 204, 255));
        rightDoorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rightDoorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorLabel.setText("Right");
        rightDoorLabel.setOpaque(true);

        accelerationLabel.setBackground(new java.awt.Color(153, 204, 255));
        accelerationLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accelerationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accelerationLabel.setText("Acceleration");
        accelerationLabel.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(213, 166, 189));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Counts");
        jLabel11.setOpaque(true);

        massDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        massDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        massDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        massDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        massDisplayLabel.setOpaque(true);

        passengersLabel.setBackground(new java.awt.Color(153, 204, 255));
        passengersLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passengersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengersLabel.setText("Passengers");
        passengersLabel.setOpaque(true);

        heightLabel.setBackground(new java.awt.Color(153, 204, 255));
        heightLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        heightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightLabel.setText("Height");
        heightLabel.setOpaque(true);

        crewLabel.setBackground(new java.awt.Color(153, 204, 255));
        crewLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        crewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crewLabel.setText("Crew");
        crewLabel.setOpaque(true);

        widthLabel.setBackground(new java.awt.Color(153, 204, 255));
        widthLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthLabel.setText("Width");
        widthLabel.setOpaque(true);

        trainIdPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        trainIdPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainIdPickerActionPerformed(evt);
            }
        });

        lengthLabel.setBackground(new java.awt.Color(153, 204, 255));
        lengthLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthLabel.setText("Length");
        lengthLabel.setOpaque(true);

        authorityDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        authorityDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        authorityDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorityDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        authorityDisplayLabel.setOpaque(true);

        numCarsLabel.setBackground(new java.awt.Color(153, 204, 255));
        numCarsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        numCarsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCarsLabel.setText("Number of Cars");
        numCarsLabel.setOpaque(true);

        powerDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        powerDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        powerDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        powerDisplayLabel.setOpaque(true);

        heightDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        heightDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        heightDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        heightDisplayLabel.setOpaque(true);

        lightsDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        lightsDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lightsDisplayLabel.setOpaque(true);

        leftDoorDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        leftDoorDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        leftDoorDisplayLabel.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(213, 166, 189));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Current");
        jLabel1.setOpaque(true);

        trainIdLabel.setBackground(new java.awt.Color(153, 204, 255));
        trainIdLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        trainIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainIdLabel.setText("Train ID");
        trainIdLabel.setBorder(new javax.swing.border.MatteBorder(null));
        trainIdLabel.setOpaque(true);

        authorityLabel.setBackground(new java.awt.Color(153, 204, 255));
        authorityLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        authorityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorityLabel.setText("Authority");
        authorityLabel.setOpaque(true);

        powerLabel.setBackground(new java.awt.Color(153, 204, 255));
        powerLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        powerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerLabel.setText("Power");
        powerLabel.setOpaque(true);

        currentTrainSpeedLabel.setBackground(new java.awt.Color(153, 204, 255));
        currentTrainSpeedLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        currentTrainSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrainSpeedLabel.setText("Current Train Speed");
        currentTrainSpeedLabel.setOpaque(true);

        lightsLabel.setBackground(new java.awt.Color(153, 204, 255));
        lightsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsLabel.setText("Lights");
        lightsLabel.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(213, 166, 189));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Doors");
        jLabel8.setOpaque(true);

        widthDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        widthDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        widthDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        widthDisplayLabel.setOpaque(true);

        lengthDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        lengthDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lengthDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lengthDisplayLabel.setOpaque(true);

        rightDoorDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        rightDoorDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rightDoorDisplayLabel.setOpaque(true);

        numCarsDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        numCarsDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        numCarsDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCarsDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCarsDisplayLabel.setOpaque(true);

        crewDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        crewDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        crewDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crewDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        crewDisplayLabel.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(213, 166, 189));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Adjust");
        jLabel2.setOpaque(true);

        debugModeGroup.add(debugModeOnButton);
        debugModeOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        debugModeOnButton.setText("ON");
        debugModeOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        debugModeGroup.add(debugModeOffButton);
        debugModeOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        debugModeOffButton.setText("OFF");
        debugModeOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debugModeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugModeOffButtonActionPerformed(evt);
            }
        });

        jLabel41.setBackground(new java.awt.Color(153, 204, 255));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Debug Mode");
        jLabel41.setOpaque(true);

        setAuthorityInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel42.setBackground(new java.awt.Color(153, 204, 255));
        jLabel42.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Emergency Brake");
        jLabel42.setOpaque(true);

        emergencyBrakeGroup.add(emergencyBrakeOnButton);
        emergencyBrakeOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeOnButton.setText("ON");
        emergencyBrakeOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        emergencyBrakeGroup.add(emergencyBrakeOffButton);
        emergencyBrakeOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeOffButton.setText("OFF");
        emergencyBrakeOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyBrakeOffButtonActionPerformed(evt);
            }
        });

        jLabel43.setBackground(new java.awt.Color(153, 204, 255));
        jLabel43.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Lights");
        jLabel43.setOpaque(true);

        lightGroup.add(lightsOnButton);
        lightsOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsOnButton.setText("ON");
        lightsOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lightGroup.add(lightsOffButton);
        lightsOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsOffButton.setText("OFF");
        lightsOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsOffButtonActionPerformed(evt);
            }
        });

        jLabel44.setBackground(new java.awt.Color(234, 153, 153));
        jLabel44.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Set Power(W)");
        jLabel44.setOpaque(true);

        setPowerInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel45.setBackground(new java.awt.Color(213, 166, 189));
        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Doors");
        jLabel45.setOpaque(true);

        jLabel46.setBackground(new java.awt.Color(153, 204, 255));
        jLabel46.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Left");
        jLabel46.setOpaque(true);

        jLabel47.setBackground(new java.awt.Color(153, 204, 255));
        jLabel47.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Right");
        jLabel47.setOpaque(true);

        leftDoorGroup.add(leftDoorOpenButton);
        leftDoorOpenButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorOpenButton.setText("OPEN");
        leftDoorOpenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorOpenButtonActionPerformed(evt);
            }
        });

        leftDoorGroup.add(leftDoorCloseButton);
        leftDoorCloseButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorCloseButton.setText("CLOSE");
        leftDoorCloseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorCloseButtonActionPerformed(evt);
            }
        });

        rightDoorGroup.add(rightDoorCloseButton);
        rightDoorCloseButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorCloseButton.setText("CLOSE");
        rightDoorCloseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorCloseButtonActionPerformed(evt);
            }
        });

        rightDoorGroup.add(rightDoorOpenButton);
        rightDoorOpenButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorOpenButton.setText("OPEN");
        rightDoorOpenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorOpenButtonActionPerformed(evt);
            }
        });

        jLabel48.setBackground(new java.awt.Color(153, 204, 255));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Set Temperture (F)");
        jLabel48.setOpaque(true);

        setTemperatureInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel49.setBackground(new java.awt.Color(153, 204, 255));
        jLabel49.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Set Authority (miles)");
        jLabel49.setOpaque(true);

        jLabel50.setBackground(new java.awt.Color(67, 67, 67));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 0, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Failures");
        jLabel50.setOpaque(true);

        jLabel51.setBackground(new java.awt.Color(255, 0, 0));
        jLabel51.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Brakes");
        jLabel51.setOpaque(true);

        jLabel52.setBackground(new java.awt.Color(255, 0, 0));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Engine");
        jLabel52.setOpaque(true);

        jLabel53.setBackground(new java.awt.Color(255, 0, 0));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Signal");
        jLabel53.setOpaque(true);

        brakesGroup.add(brakeFailureOnButton);
        brakeFailureOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        brakeFailureOnButton.setText("ON");
        brakeFailureOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        brakesGroup.add(brakeFailureOffButton);
        brakeFailureOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        brakeFailureOffButton.setText("OFF");
        brakeFailureOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brakeFailureOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brakeFailureOffButtonActionPerformed(evt);
            }
        });

        engineGroup.add(enginFailureOnButton);
        enginFailureOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        enginFailureOnButton.setText("ON");
        enginFailureOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        engineGroup.add(engineFailureOffButton);
        engineFailureOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        engineFailureOffButton.setText("OFF");
        engineFailureOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        engineFailureOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineFailureOffButtonActionPerformed(evt);
            }
        });

        signalGroup.add(signalFailureOnButton);
        signalFailureOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        signalFailureOnButton.setText("ON");
        signalFailureOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        signalGroup.add(signalFailureOffButton);
        signalFailureOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        signalFailureOffButton.setText("OFF");
        signalFailureOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signalFailureOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalFailureOffButtonActionPerformed(evt);
            }
        });

        applyChangesButton.setBackground(new java.awt.Color(255, 229, 153));
        applyChangesButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        applyChangesButton.setText("APPLY CHANGES");
        applyChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangesButtonActionPerformed(evt);
            }
        });

        timeLabel.setBackground(new java.awt.Color(153, 204, 255));
        timeLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time(s)");
        timeLabel.setOpaque(true);

        setTimeInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(authorityDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(accelerationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accelerationDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentTrainSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(currentTrainSpeedDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lightsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lightsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(emergencyBrakeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(emergencyBrakeDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(leftDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(massLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(massDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rightDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(rightDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(heightDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(widthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trainIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(trainIdPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(temperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperatureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(powerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(powerDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(debugModeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(debugModeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emergencyBrakeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emergencyBrakeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lightsOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lightsOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(setPowerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(setTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leftDoorOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leftDoorCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setTemperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setAuthorityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightDoorOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightDoorCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passengersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passengersDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCarsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brakeFailureOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brakeFailureOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enginFailureOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineFailureOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signalFailureOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signalFailureOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(applyChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(debugModeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(debugModeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emergencyBrakeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(emergencyBrakeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lightsOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lightsOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setPowerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leftDoorOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(leftDoorCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rightDoorOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(rightDoorCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(setTemperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(setAuthorityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(trainIdPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(temperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accelerationDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accelerationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(authorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(authorityDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(powerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(powerDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentTrainSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentTrainSpeedDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lightsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lightsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emergencyBrakeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emergencyBrakeDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leftDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leftDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(massLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(massDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rightDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rightDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heightDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(widthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passengersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(crewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passengersDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(crewDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(numCarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lengthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(numCarsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(brakeFailureOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(brakeFailureOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enginFailureOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(engineFailureOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signalFailureOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(signalFailureOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(applyChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debugModeOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugModeOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debugModeOffButtonActionPerformed

    private void emergencyBrakeOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyBrakeOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyBrakeOffButtonActionPerformed

    private void lightsOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightsOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightsOffButtonActionPerformed

    private void leftDoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorOpenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftDoorOpenButtonActionPerformed

    private void leftDoorCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorCloseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftDoorCloseButtonActionPerformed

    private void rightDoorCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorCloseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightDoorCloseButtonActionPerformed

    private void rightDoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorOpenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightDoorOpenButtonActionPerformed

    private void brakeFailureOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brakeFailureOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brakeFailureOffButtonActionPerformed

    private void engineFailureOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineFailureOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineFailureOffButtonActionPerformed

    private void signalFailureOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signalFailureOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signalFailureOffButtonActionPerformed

    private void applyChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangesButtonActionPerformed
        // TODO add your handling code here:

        if(debugModeOnButton.isSelected()){
            //debug mode is on
            //Train test = new Train();
            //Get velocity from new power
            //test.setTime(Double.parseDouble(setTimeInput.getText()));
            //test.setPower(Double.parseDouble(setPowerInput.getText()));
            //currentTrainSpeedDisplayLabel.setText(String.format("%.2f", test.getVelocity()) + " MPH");


            //take temperature and display it
            temperatureDisplayLabel.setText(setTemperatureInput.getText() + " F");
            //take power and display it
            powerDisplayLabel.setText(setPowerInput.getText() + " W");
            //take authority and display it
            authorityDisplayLabel.setText(setAuthorityInput.getText() + " mi");

            if(emergencyBrakeOnButton.isSelected()){
                //emergency brake on
                emergencyBrakeDisplayLabel.setText("ON");
            }
            else if(emergencyBrakeOffButton.isSelected()){
                //emergency brake off
                emergencyBrakeDisplayLabel.setText("OFF");
            }

            if(lightsOnButton.isSelected()){
                //lights on
                lightsDisplayLabel.setText("ON");
            }
            else if(lightsOffButton.isSelected()){
                //lights off
                lightsDisplayLabel.setText("OFF");
            }

            if(leftDoorOpenButton.isSelected()){
                //left door open
                leftDoorDisplayLabel.setText("OPEN");
            }
            else if(leftDoorCloseButton.isSelected()){
                //left door closed
                leftDoorDisplayLabel.setText("CLOSED");
            }

            if(rightDoorOpenButton.isSelected()){
                //right door open
                rightDoorDisplayLabel.setText("OPEN");
            }
            else if(rightDoorCloseButton.isSelected()){
                //right door closed
                rightDoorDisplayLabel.setText("CLOSED");
            }

        }
        //debug is off
        else{
            String infoMessage = "Please turn on Debug mode to apply changes.";
            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_applyChangesButtonActionPerformed

    private void trainIdPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainIdPickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainIdPickerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainModelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accelerationDisplayLabel;
    private javax.swing.JLabel accelerationLabel;
    private javax.swing.JButton applyChangesButton;
    private javax.swing.JLabel authorityDisplayLabel;
    private javax.swing.JLabel authorityLabel;
    private javax.swing.JRadioButton brakeFailureOffButton;
    private javax.swing.JRadioButton brakeFailureOnButton;
    private javax.swing.ButtonGroup brakesGroup;
    private javax.swing.JLabel crewDisplayLabel;
    private javax.swing.JLabel crewLabel;
    private javax.swing.JLabel currentTrainSpeedDisplayLabel;
    private javax.swing.JLabel currentTrainSpeedLabel;
    private javax.swing.ButtonGroup debugModeGroup;
    private javax.swing.JRadioButton debugModeOffButton;
    private javax.swing.JRadioButton debugModeOnButton;
    private javax.swing.JLabel emergencyBrakeDisplayLabel;
    private javax.swing.ButtonGroup emergencyBrakeGroup;
    private javax.swing.JLabel emergencyBrakeLabel;
    private javax.swing.JRadioButton emergencyBrakeOffButton;
    private javax.swing.JRadioButton emergencyBrakeOnButton;
    private javax.swing.JRadioButton enginFailureOnButton;
    private javax.swing.JRadioButton engineFailureOffButton;
    private javax.swing.ButtonGroup engineGroup;
    private javax.swing.JLabel heightDisplayLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton leftDoorCloseButton;
    private javax.swing.JLabel leftDoorDisplayLabel;
    private javax.swing.ButtonGroup leftDoorGroup;
    private javax.swing.JLabel leftDoorLabel;
    private javax.swing.JRadioButton leftDoorOpenButton;
    private javax.swing.JLabel lengthDisplayLabel;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.ButtonGroup lightGroup;
    private javax.swing.JLabel lightsDisplayLabel;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JRadioButton lightsOffButton;
    private javax.swing.JRadioButton lightsOnButton;
    private javax.swing.JLabel massDisplayLabel;
    private javax.swing.JLabel massLabel;
    private javax.swing.JLabel numCarsDisplayLabel;
    private javax.swing.JLabel numCarsLabel;
    private javax.swing.JLabel passengersDisplayLabel;
    private javax.swing.JLabel passengersLabel;
    private javax.swing.JLabel powerDisplayLabel;
    private javax.swing.JLabel powerLabel;
    private javax.swing.JRadioButton rightDoorCloseButton;
    private javax.swing.JLabel rightDoorDisplayLabel;
    private javax.swing.ButtonGroup rightDoorGroup;
    private javax.swing.JLabel rightDoorLabel;
    private javax.swing.JRadioButton rightDoorOpenButton;
    private javax.swing.JTextField setAuthorityInput;
    private javax.swing.JTextField setPowerInput;
    private javax.swing.JTextField setTemperatureInput;
    private javax.swing.JTextField setTimeInput;
    private javax.swing.JRadioButton signalFailureOffButton;
    private javax.swing.JRadioButton signalFailureOnButton;
    private javax.swing.ButtonGroup signalGroup;
    private javax.swing.JLabel temperatureDisplayLabel;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel trainIdLabel;
    private javax.swing.JComboBox<String> trainIdPicker;
    private javax.swing.JLabel widthDisplayLabel;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
