/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainmodel;

import javax.swing.JOptionPane;
import javax.*;
import java.*;
import static java.lang.String.valueOf;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Parth
 */
public class TrainModelGUI extends javax.swing.JFrame {

    /**
     * Creates new form TrainModelGUI
     */
    public TrainModelGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        debugModeGroup = new javax.swing.ButtonGroup();
        emergencyBrakeGroup = new javax.swing.ButtonGroup();
        lightGroup = new javax.swing.ButtonGroup();
        leftDoorGroup = new javax.swing.ButtonGroup();
        rightDoorGroup = new javax.swing.ButtonGroup();
        brakesGroup = new javax.swing.ButtonGroup();
        engineGroup = new javax.swing.ButtonGroup();
        signalGroup = new javax.swing.ButtonGroup();
        passengersDisplayLabel = new javax.swing.JLabel();
        currentTrainSpeedDisplayLabel = new javax.swing.JLabel();
        massLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        speedLimitLabel = new javax.swing.JLabel();
        emergencyBrakeLabel = new javax.swing.JLabel();
        speedLimitDisplayLabel = new javax.swing.JLabel();
        temperatureDisplayLabel = new javax.swing.JLabel();
        accelerationDisplayLabel = new javax.swing.JLabel();
        emergencyBrakeDisplayLabel = new javax.swing.JLabel();
        leftDoorLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rightDoorLabel = new javax.swing.JLabel();
        accelerationLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        massDisplayLabel = new javax.swing.JLabel();
        passengersLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        crewLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        trainIdPicker = new javax.swing.JComboBox<>();
        lengthLabel = new javax.swing.JLabel();
        authorityDisplayLabel = new javax.swing.JLabel();
        numCarsLabel = new javax.swing.JLabel();
        powerDisplayLabel = new javax.swing.JLabel();
        heightDisplayLabel = new javax.swing.JLabel();
        lightsDisplayLabel = new javax.swing.JLabel();
        leftDoorDisplayLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        trainIdLabel = new javax.swing.JLabel();
        authorityLabel = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();
        currentTrainSpeedLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        widthDisplayLabel = new javax.swing.JLabel();
        lengthDisplayLabel = new javax.swing.JLabel();
        rightDoorDisplayLabel = new javax.swing.JLabel();
        numCarsDisplayLabel = new javax.swing.JLabel();
        crewDisplayLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        debugModeOnButton = new javax.swing.JRadioButton();
        debugModeOffButton = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        setAuthorityInput = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        emergencyBrakeOnButton = new javax.swing.JRadioButton();
        emergencyBrakeOffButton = new javax.swing.JRadioButton();
        jLabel43 = new javax.swing.JLabel();
        lightsOnButton = new javax.swing.JRadioButton();
        lightsOffButton = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        setPowerInput = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        leftDoorOpenButton = new javax.swing.JRadioButton();
        leftDoorCloseButton = new javax.swing.JRadioButton();
        rightDoorCloseButton = new javax.swing.JRadioButton();
        rightDoorOpenButton = new javax.swing.JRadioButton();
        jLabel48 = new javax.swing.JLabel();
        setTemperatureInput = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        brakeFailureOnButton = new javax.swing.JRadioButton();
        brakeFailureOffButton = new javax.swing.JRadioButton();
        enginFailureOnButton = new javax.swing.JRadioButton();
        engineFailureOffButton = new javax.swing.JRadioButton();
        signalFailureOnButton = new javax.swing.JRadioButton();
        signalFailureOffButton = new javax.swing.JRadioButton();
        applyChangesButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        setTimeInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passengersDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        passengersDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        passengersDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengersDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        passengersDisplayLabel.setOpaque(true);
        getContentPane().add(passengersDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 411, 75, 32));

        currentTrainSpeedDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        currentTrainSpeedDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        currentTrainSpeedDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrainSpeedDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        currentTrainSpeedDisplayLabel.setOpaque(true);
        getContentPane().add(currentTrainSpeedDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 177, 75, 32));

        massLabel.setBackground(new java.awt.Color(153, 204, 255));
        massLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        massLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        massLabel.setText("Mass");
        massLabel.setOpaque(true);
        getContentPane().add(massLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 294, 136, 32));

        temperatureLabel.setBackground(new java.awt.Color(153, 204, 255));
        temperatureLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temperatureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureLabel.setText("Temperature");
        temperatureLabel.setOpaque(true);
        getContentPane().add(temperatureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 99, 165, 32));

        speedLimitLabel.setBackground(new java.awt.Color(153, 204, 255));
        speedLimitLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        speedLimitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        speedLimitLabel.setText("Speed Limit");
        speedLimitLabel.setOpaque(true);
        getContentPane().add(speedLimitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 165, 32));

        emergencyBrakeLabel.setBackground(new java.awt.Color(153, 204, 255));
        emergencyBrakeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emergencyBrakeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeLabel.setText("Emergency Brake");
        emergencyBrakeLabel.setOpaque(true);
        getContentPane().add(emergencyBrakeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 216, 165, 32));

        speedLimitDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        speedLimitDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        speedLimitDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        speedLimitDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        speedLimitDisplayLabel.setOpaque(true);
        getContentPane().add(speedLimitDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 60, 75, 32));

        temperatureDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        temperatureDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        temperatureDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        temperatureDisplayLabel.setOpaque(true);
        getContentPane().add(temperatureDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 99, 75, 32));

        accelerationDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        accelerationDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        accelerationDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accelerationDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        accelerationDisplayLabel.setOpaque(true);
        getContentPane().add(accelerationDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 138, 75, 32));

        emergencyBrakeDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        emergencyBrakeDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emergencyBrakeDisplayLabel.setOpaque(true);
        getContentPane().add(emergencyBrakeDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 216, 75, 32));

        leftDoorLabel.setBackground(new java.awt.Color(153, 204, 255));
        leftDoorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        leftDoorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorLabel.setText("Left");
        leftDoorLabel.setOpaque(true);
        getContentPane().add(leftDoorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 294, 97, 32));

        jLabel30.setBackground(new java.awt.Color(213, 166, 189));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Dimensions");
        jLabel30.setOpaque(true);
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 255, 247, 32));

        rightDoorLabel.setBackground(new java.awt.Color(153, 204, 255));
        rightDoorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rightDoorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorLabel.setText("Right");
        rightDoorLabel.setOpaque(true);
        getContentPane().add(rightDoorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 333, 97, 32));

        accelerationLabel.setBackground(new java.awt.Color(153, 204, 255));
        accelerationLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accelerationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accelerationLabel.setText("Acceleration");
        accelerationLabel.setOpaque(true);
        getContentPane().add(accelerationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 138, 165, 32));

        jLabel11.setBackground(new java.awt.Color(213, 166, 189));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Counts");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 372, 179, 32));

        massDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        massDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        massDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        massDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        massDisplayLabel.setOpaque(true);
        getContentPane().add(massDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 294, 75, 32));

        passengersLabel.setBackground(new java.awt.Color(153, 204, 255));
        passengersLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passengersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengersLabel.setText("Passengers");
        passengersLabel.setOpaque(true);
        getContentPane().add(passengersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 411, 97, 32));

        heightLabel.setBackground(new java.awt.Color(153, 204, 255));
        heightLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        heightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightLabel.setText("Height");
        heightLabel.setOpaque(true);
        getContentPane().add(heightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 333, 136, 32));

        crewLabel.setBackground(new java.awt.Color(153, 204, 255));
        crewLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        crewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crewLabel.setText("Crew");
        crewLabel.setOpaque(true);
        getContentPane().add(crewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 450, 97, 32));

        widthLabel.setBackground(new java.awt.Color(153, 204, 255));
        widthLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthLabel.setText("Width");
        widthLabel.setOpaque(true);
        getContentPane().add(widthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 372, 136, 32));

        trainIdPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(trainIdPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 65, 77, -1));

        lengthLabel.setBackground(new java.awt.Color(153, 204, 255));
        lengthLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthLabel.setText("Length");
        lengthLabel.setOpaque(true);
        getContentPane().add(lengthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 411, 136, 32));

        authorityDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        authorityDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        authorityDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorityDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        authorityDisplayLabel.setOpaque(true);
        getContentPane().add(authorityDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 99, 75, 32));

        numCarsLabel.setBackground(new java.awt.Color(153, 204, 255));
        numCarsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        numCarsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCarsLabel.setText("Number of Cars");
        numCarsLabel.setOpaque(true);
        getContentPane().add(numCarsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 136, 32));

        powerDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        powerDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        powerDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        powerDisplayLabel.setOpaque(true);
        getContentPane().add(powerDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 138, 75, 32));

        heightDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        heightDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        heightDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        heightDisplayLabel.setOpaque(true);
        getContentPane().add(heightDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 333, 75, 32));

        lightsDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        lightsDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lightsDisplayLabel.setOpaque(true);
        getContentPane().add(lightsDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 216, 75, 32));

        leftDoorDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        leftDoorDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        leftDoorDisplayLabel.setOpaque(true);
        getContentPane().add(leftDoorDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 294, 75, 32));

        jLabel1.setBackground(new java.awt.Color(213, 166, 189));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Current");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 465, 40));

        trainIdLabel.setBackground(new java.awt.Color(153, 204, 255));
        trainIdLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        trainIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainIdLabel.setText("Train ID");
        trainIdLabel.setBorder(new javax.swing.border.MatteBorder(null));
        trainIdLabel.setOpaque(true);
        getContentPane().add(trainIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 97, 32));

        authorityLabel.setBackground(new java.awt.Color(153, 204, 255));
        authorityLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        authorityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorityLabel.setText("Authority");
        authorityLabel.setOpaque(true);
        getContentPane().add(authorityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, 97, 32));

        powerLabel.setBackground(new java.awt.Color(153, 204, 255));
        powerLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        powerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerLabel.setText("Power");
        powerLabel.setOpaque(true);
        getContentPane().add(powerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 138, 97, 32));

        currentTrainSpeedLabel.setBackground(new java.awt.Color(153, 204, 255));
        currentTrainSpeedLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        currentTrainSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrainSpeedLabel.setText("Current Train Speed");
        currentTrainSpeedLabel.setOpaque(true);
        getContentPane().add(currentTrainSpeedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, 165, 32));

        lightsLabel.setBackground(new java.awt.Color(153, 204, 255));
        lightsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsLabel.setText("Lights");
        lightsLabel.setOpaque(true);
        getContentPane().add(lightsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 216, 97, 32));

        jLabel8.setBackground(new java.awt.Color(213, 166, 189));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Doors");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 255, 179, 32));

        widthDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        widthDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        widthDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        widthDisplayLabel.setOpaque(true);
        getContentPane().add(widthDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 372, 75, 32));

        lengthDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        lengthDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lengthDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lengthDisplayLabel.setOpaque(true);
        getContentPane().add(lengthDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 411, 75, 32));

        rightDoorDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        rightDoorDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rightDoorDisplayLabel.setOpaque(true);
        getContentPane().add(rightDoorDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 333, 75, 32));

        numCarsDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        numCarsDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        numCarsDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCarsDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCarsDisplayLabel.setOpaque(true);
        getContentPane().add(numCarsDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 450, 75, 32));

        crewDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        crewDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        crewDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crewDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        crewDisplayLabel.setOpaque(true);
        getContentPane().add(crewDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 450, 75, 32));

        jLabel2.setBackground(new java.awt.Color(213, 166, 189));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Adjust");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 13, 477, 40));

        debugModeGroup.add(debugModeOnButton);
        debugModeOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        debugModeOnButton.setText("ON");
        debugModeOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(debugModeOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 61, 64, 53));

        debugModeGroup.add(debugModeOffButton);
        debugModeOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        debugModeOffButton.setText("OFF");
        debugModeOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debugModeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugModeOffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(debugModeOffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 60, 63, 54));

        jLabel41.setBackground(new java.awt.Color(153, 204, 255));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Debug Mode");
        jLabel41.setOpaque(true);
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 60, 175, 53));

        setAuthorityInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(setAuthorityInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 70, 48));

        jLabel42.setBackground(new java.awt.Color(153, 204, 255));
        jLabel42.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Emergency Brake");
        jLabel42.setOpaque(true);
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 120, 158, 63));

        emergencyBrakeGroup.add(emergencyBrakeOnButton);
        emergencyBrakeOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeOnButton.setText("ON");
        emergencyBrakeOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(emergencyBrakeOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 120, 63, 33));

        emergencyBrakeGroup.add(emergencyBrakeOffButton);
        emergencyBrakeOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeOffButton.setText("OFF");
        emergencyBrakeOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyBrakeOffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(emergencyBrakeOffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 153, 63, 30));

        jLabel43.setBackground(new java.awt.Color(153, 204, 255));
        jLabel43.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Lights");
        jLabel43.setOpaque(true);
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 120, 158, 63));

        lightGroup.add(lightsOnButton);
        lightsOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsOnButton.setText("ON");
        lightsOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lightsOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 120, 63, 33));

        lightGroup.add(lightsOffButton);
        lightsOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsOffButton.setText("OFF");
        lightsOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsOffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lightsOffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 153, 63, 30));

        jLabel44.setBackground(new java.awt.Color(234, 153, 153));
        jLabel44.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Set Power(W)");
        jLabel44.setOpaque(true);
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 190, 176, 48));

        setPowerInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(setPowerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 190, 70, 48));

        jLabel45.setBackground(new java.awt.Color(213, 166, 189));
        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Doors");
        jLabel45.setOpaque(true);
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 190, 221, 32));

        jLabel46.setBackground(new java.awt.Color(153, 204, 255));
        jLabel46.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Left");
        jLabel46.setOpaque(true);
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 229, 97, 63));

        jLabel47.setBackground(new java.awt.Color(153, 204, 255));
        jLabel47.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Right");
        jLabel47.setOpaque(true);
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 299, 97, 65));

        leftDoorGroup.add(leftDoorOpenButton);
        leftDoorOpenButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorOpenButton.setText("OPEN");
        leftDoorOpenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorOpenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(leftDoorOpenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 229, 90, 33));

        leftDoorGroup.add(leftDoorCloseButton);
        leftDoorCloseButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorCloseButton.setText("CLOSE");
        leftDoorCloseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorCloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(leftDoorCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 262, 90, 30));

        rightDoorGroup.add(rightDoorCloseButton);
        rightDoorCloseButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorCloseButton.setText("CLOSE");
        rightDoorCloseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorCloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rightDoorCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 329, 90, 35));

        rightDoorGroup.add(rightDoorOpenButton);
        rightDoorOpenButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorOpenButton.setText("OPEN");
        rightDoorOpenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorOpenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rightDoorOpenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 299, 90, 30));

        jLabel48.setBackground(new java.awt.Color(153, 204, 255));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Set Temperture (F)");
        jLabel48.setOpaque(true);
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 176, 46));

        setTemperatureInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(setTemperatureInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 70, 46));

        jLabel49.setBackground(new java.awt.Color(153, 204, 255));
        jLabel49.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Set Authority (miles)");
        jLabel49.setOpaque(true);
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 176, 48));

        jLabel50.setBackground(new java.awt.Color(67, 67, 67));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 0, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Failures");
        jLabel50.setOpaque(true);
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 251, 32));

        jLabel51.setBackground(new java.awt.Color(255, 0, 0));
        jLabel51.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Brakes");
        jLabel51.setOpaque(true);
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 136, 60));

        jLabel52.setBackground(new java.awt.Color(255, 0, 0));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Engine");
        jLabel52.setOpaque(true);
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 136, 60));

        jLabel53.setBackground(new java.awt.Color(255, 0, 0));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Signal");
        jLabel53.setOpaque(true);
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 136, 60));

        brakesGroup.add(brakeFailureOnButton);
        brakeFailureOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        brakeFailureOnButton.setText("ON");
        brakeFailureOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(brakeFailureOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 63, 30));

        brakesGroup.add(brakeFailureOffButton);
        brakeFailureOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        brakeFailureOffButton.setText("OFF");
        brakeFailureOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brakeFailureOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brakeFailureOffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(brakeFailureOffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 63, 30));

        engineGroup.add(enginFailureOnButton);
        enginFailureOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        enginFailureOnButton.setText("ON");
        enginFailureOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(enginFailureOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 63, 30));

        engineGroup.add(engineFailureOffButton);
        engineFailureOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        engineFailureOffButton.setText("OFF");
        engineFailureOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        engineFailureOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineFailureOffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(engineFailureOffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 63, 30));

        signalGroup.add(signalFailureOnButton);
        signalFailureOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        signalFailureOnButton.setText("ON");
        signalFailureOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(signalFailureOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 63, 30));

        signalGroup.add(signalFailureOffButton);
        signalFailureOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        signalFailureOffButton.setText("OFF");
        signalFailureOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signalFailureOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalFailureOffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signalFailureOffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 63, 30));

        applyChangesButton.setBackground(new java.awt.Color(255, 229, 153));
        applyChangesButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        applyChangesButton.setText("APPLY CHANGES");
        applyChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(applyChangesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 477, 46));

        timeLabel.setBackground(new java.awt.Color(153, 204, 255));
        timeLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time(s)");
        timeLabel.setOpaque(true);
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 176, 46));

        setTimeInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(setTimeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 70, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debugModeOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugModeOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debugModeOffButtonActionPerformed

    private void emergencyBrakeOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyBrakeOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyBrakeOffButtonActionPerformed

    private void lightsOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightsOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightsOffButtonActionPerformed

    private void leftDoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorOpenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftDoorOpenButtonActionPerformed

    private void leftDoorCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorCloseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftDoorCloseButtonActionPerformed

    private void rightDoorCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorCloseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightDoorCloseButtonActionPerformed

    private void rightDoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorOpenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightDoorOpenButtonActionPerformed

    private void brakeFailureOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brakeFailureOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brakeFailureOffButtonActionPerformed

    private void engineFailureOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineFailureOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineFailureOffButtonActionPerformed

    private void signalFailureOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signalFailureOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signalFailureOffButtonActionPerformed

    private void applyChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangesButtonActionPerformed
        // TODO add your handling code here:
        
        if(debugModeOnButton.isSelected()){
            //debug mode is on
            Train test = new Train();
            //Get velocity from new power
            test.setTime(Double.parseDouble(setTimeInput.getText()));
            test.setPower(Double.parseDouble(setPowerInput.getText()));
            currentTrainSpeedDisplayLabel.setText(String.format("%.2f", test.getVelocity()) + " MPH");

            
            //take temperature and display it
            temperatureDisplayLabel.setText(setTemperatureInput.getText() + " F");
            //take power and display it
            powerDisplayLabel.setText(setPowerInput.getText() + " W");
            //take authority and display it
            authorityDisplayLabel.setText(setAuthorityInput.getText() + " mi");
            
            if(emergencyBrakeOnButton.isSelected()){
                //emergency brake on
                emergencyBrakeDisplayLabel.setText("ON");
            }
            else if(emergencyBrakeOffButton.isSelected()){
                //emergency brake off
                emergencyBrakeDisplayLabel.setText("OFF");
            }
            
            if(lightsOnButton.isSelected()){
                //lights on
                lightsDisplayLabel.setText("ON");
            }
            else if(lightsOffButton.isSelected()){
                //lights off
                lightsDisplayLabel.setText("OFF");
            }
            
            if(leftDoorOpenButton.isSelected()){
                //left door open
                leftDoorDisplayLabel.setText("OPEN");
            }
            else if(leftDoorCloseButton.isSelected()){
                //left door closed
                leftDoorDisplayLabel.setText("CLOSED");
            }
            
            if(rightDoorOpenButton.isSelected()){
                //right door open
                rightDoorDisplayLabel.setText("OPEN");
            }
            else if(rightDoorCloseButton.isSelected()){
                //right door closed
                rightDoorDisplayLabel.setText("CLOSED");
            }
            
        }
        //debug is off
        else{
            String infoMessage = "Please turn on Debug mode to apply changes.";
            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_applyChangesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainModelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accelerationDisplayLabel;
    private javax.swing.JLabel accelerationLabel;
    private javax.swing.JButton applyChangesButton;
    private javax.swing.JLabel authorityDisplayLabel;
    private javax.swing.JLabel authorityLabel;
    private javax.swing.JRadioButton brakeFailureOffButton;
    private javax.swing.JRadioButton brakeFailureOnButton;
    private javax.swing.ButtonGroup brakesGroup;
    private javax.swing.JLabel crewDisplayLabel;
    private javax.swing.JLabel crewLabel;
    private javax.swing.JLabel currentTrainSpeedDisplayLabel;
    private javax.swing.JLabel currentTrainSpeedLabel;
    private javax.swing.ButtonGroup debugModeGroup;
    private javax.swing.JRadioButton debugModeOffButton;
    private javax.swing.JRadioButton debugModeOnButton;
    private javax.swing.JLabel emergencyBrakeDisplayLabel;
    private javax.swing.ButtonGroup emergencyBrakeGroup;
    private javax.swing.JLabel emergencyBrakeLabel;
    private javax.swing.JRadioButton emergencyBrakeOffButton;
    private javax.swing.JRadioButton emergencyBrakeOnButton;
    private javax.swing.JRadioButton enginFailureOnButton;
    private javax.swing.JRadioButton engineFailureOffButton;
    private javax.swing.ButtonGroup engineGroup;
    private javax.swing.JLabel heightDisplayLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton leftDoorCloseButton;
    private javax.swing.JLabel leftDoorDisplayLabel;
    private javax.swing.ButtonGroup leftDoorGroup;
    private javax.swing.JLabel leftDoorLabel;
    private javax.swing.JRadioButton leftDoorOpenButton;
    private javax.swing.JLabel lengthDisplayLabel;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.ButtonGroup lightGroup;
    private javax.swing.JLabel lightsDisplayLabel;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JRadioButton lightsOffButton;
    private javax.swing.JRadioButton lightsOnButton;
    private javax.swing.JLabel massDisplayLabel;
    private javax.swing.JLabel massLabel;
    private javax.swing.JLabel numCarsDisplayLabel;
    private javax.swing.JLabel numCarsLabel;
    private javax.swing.JLabel passengersDisplayLabel;
    private javax.swing.JLabel passengersLabel;
    private javax.swing.JLabel powerDisplayLabel;
    private javax.swing.JLabel powerLabel;
    private javax.swing.JRadioButton rightDoorCloseButton;
    private javax.swing.JLabel rightDoorDisplayLabel;
    private javax.swing.ButtonGroup rightDoorGroup;
    private javax.swing.JLabel rightDoorLabel;
    private javax.swing.JRadioButton rightDoorOpenButton;
    private javax.swing.JTextField setAuthorityInput;
    private javax.swing.JTextField setPowerInput;
    private javax.swing.JTextField setTemperatureInput;
    private javax.swing.JTextField setTimeInput;
    private javax.swing.JRadioButton signalFailureOffButton;
    private javax.swing.JRadioButton signalFailureOnButton;
    private javax.swing.ButtonGroup signalGroup;
    private javax.swing.JLabel speedLimitDisplayLabel;
    private javax.swing.JLabel speedLimitLabel;
    private javax.swing.JLabel temperatureDisplayLabel;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel trainIdLabel;
    private javax.swing.JComboBox<String> trainIdPicker;
    private javax.swing.JLabel widthDisplayLabel;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
