/*   ______                 _           _
 *  /_  __/ _____  ____ _  (_) ____    (_) ____    ____ _
 *   / /   / ___/ / __ `/ / / / __ \  / / / __ \  / __ `/
 *  / /   / /    / /_/ / / / / / / / / / / / / / / /_/ /
 * /_/   /_/     \__,_/ /_/ /_/ /_/ /_/ /_/ /_/  \__, /
 *                                              /____/
 *     __  ___                 __
 *    /  |/  / ____    ____   / /_  ____ _  ____ _  ___
 *   / /|_/ / / __ \  / __ \ / __/ / __ `/ / __ `/ / _ \
 *  / /  / / / /_/ / / / / // /_  / /_/ / / /_/ / /  __/
 * /_/  /_/  \____/ /_/ /_/ \__/  \__,_/  \__, /  \___/
 *                                       /____/
 *
 * @author Parth Dadhania
 */
package trainmodel;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.*;
import static java.lang.String.valueOf;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Parth
 */
public class TrainModelGUI extends javax.swing.JFrame {

    Train myTrain;
    public TrainModelGUI() {
        initComponents();
    }

    public TrainModelGUI(Train train) {
        myTrain = train;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        debugModeGroup = new javax.swing.ButtonGroup();
        emergencyBrakeGroup = new javax.swing.ButtonGroup();
        lightGroup = new javax.swing.ButtonGroup();
        leftDoorGroup = new javax.swing.ButtonGroup();
        rightDoorGroup = new javax.swing.ButtonGroup();
        brakesGroup = new javax.swing.ButtonGroup();
        engineGroup = new javax.swing.ButtonGroup();
        signalGroup = new javax.swing.ButtonGroup();
        passengersDisplayLabel = new javax.swing.JLabel();
        currentTrainSpeedDisplayLabel = new javax.swing.JLabel();
        massLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        emergencyBrakeLabel = new javax.swing.JLabel();
        temperatureDisplayLabel = new javax.swing.JLabel();
        accelerationDisplayLabel = new javax.swing.JLabel();
        emergencyBrakeDisplayLabel = new javax.swing.JLabel();
        leftDoorLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rightDoorLabel = new javax.swing.JLabel();
        accelerationLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        massDisplayLabel = new javax.swing.JLabel();
        passengersLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        crewLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        trainIdPicker = new javax.swing.JComboBox<>();
        lengthLabel = new javax.swing.JLabel();
        authorityDisplayLabel = new javax.swing.JLabel();
        numCarsLabel = new javax.swing.JLabel();
        powerDisplayLabel = new javax.swing.JLabel();
        heightDisplayLabel = new javax.swing.JLabel();
        lightsDisplayLabel = new javax.swing.JLabel();
        leftDoorDisplayLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        trainIdLabel = new javax.swing.JLabel();
        authorityLabel = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();
        currentTrainSpeedLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        widthDisplayLabel = new javax.swing.JLabel();
        lengthDisplayLabel = new javax.swing.JLabel();
        rightDoorDisplayLabel = new javax.swing.JLabel();
        numCarsDisplayLabel = new javax.swing.JLabel();
        crewDisplayLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        debugModeOnButton = new javax.swing.JRadioButton();
        debugModeOffButton = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        setAuthorityInput = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        setPowerInput = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        setTemperatureInput = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        applyChangesButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        messageBoardDisplayLabel = new javax.swing.JLabel();
        brakeFailure = new javax.swing.JButton();
        engineFailure = new javax.swing.JButton();
        signalFailure = new javax.swing.JButton();
        leftOpen = new javax.swing.JButton();
        leftClose = new javax.swing.JButton();
        rightOpen = new javax.swing.JButton();
        rightClose = new javax.swing.JButton();
        lightsOn = new javax.swing.JButton();
        lightsOff = new javax.swing.JButton();
        emergencyBrakeButton = new javax.swing.JButton();
        suggestedSpeedLabel = new javax.swing.JLabel();
        suggestedSpeedDisplay = new javax.swing.JLabel();
        setTitle("TrainModelGUI Train: " + myTrain.getTrainId());
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);

        passengersDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        passengersDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        passengersDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengersDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        passengersDisplayLabel.setOpaque(true);

        currentTrainSpeedDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        currentTrainSpeedDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        currentTrainSpeedDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrainSpeedDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        currentTrainSpeedDisplayLabel.setOpaque(true);

        massLabel.setBackground(new java.awt.Color(153, 204, 255));
        massLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        massLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        massLabel.setText("Mass");
        massLabel.setOpaque(true);

        temperatureLabel.setBackground(new java.awt.Color(153, 204, 255));
        temperatureLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temperatureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureLabel.setText("Temperature");
        temperatureLabel.setOpaque(true);

        emergencyBrakeLabel.setBackground(new java.awt.Color(153, 204, 255));
        emergencyBrakeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emergencyBrakeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeLabel.setText("Emergency Brake");
        emergencyBrakeLabel.setOpaque(true);

        temperatureDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        temperatureDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        temperatureDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        temperatureDisplayLabel.setOpaque(true);

        accelerationDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        accelerationDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        accelerationDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accelerationDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        accelerationDisplayLabel.setOpaque(true);

        emergencyBrakeDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        emergencyBrakeDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        emergencyBrakeDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyBrakeDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emergencyBrakeDisplayLabel.setOpaque(true);

        leftDoorLabel.setBackground(new java.awt.Color(153, 204, 255));
        leftDoorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        leftDoorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorLabel.setText("Left");
        leftDoorLabel.setOpaque(true);

        jLabel30.setBackground(new java.awt.Color(213, 166, 189));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Dimensions");
        jLabel30.setOpaque(true);

        rightDoorLabel.setBackground(new java.awt.Color(153, 204, 255));
        rightDoorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rightDoorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorLabel.setText("Right");
        rightDoorLabel.setOpaque(true);

        accelerationLabel.setBackground(new java.awt.Color(153, 204, 255));
        accelerationLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accelerationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accelerationLabel.setText("Acceleration");
        accelerationLabel.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(213, 166, 189));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Counts");
        jLabel11.setOpaque(true);

        massDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        massDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        massDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        massDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        massDisplayLabel.setOpaque(true);

        passengersLabel.setBackground(new java.awt.Color(153, 204, 255));
        passengersLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passengersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengersLabel.setText("Passengers");
        passengersLabel.setOpaque(true);

        heightLabel.setBackground(new java.awt.Color(153, 204, 255));
        heightLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        heightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightLabel.setText("Height");
        heightLabel.setOpaque(true);

        crewLabel.setBackground(new java.awt.Color(153, 204, 255));
        crewLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        crewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crewLabel.setText("Crew");
        crewLabel.setOpaque(true);

        widthLabel.setBackground(new java.awt.Color(153, 204, 255));
        widthLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthLabel.setText("Width");
        widthLabel.setOpaque(true);

        trainIdPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        trainIdPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainIdPickerActionPerformed(evt);
            }
        });

        lengthLabel.setBackground(new java.awt.Color(153, 204, 255));
        lengthLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthLabel.setText("Length");
        lengthLabel.setOpaque(true);

        authorityDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        authorityDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        authorityDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorityDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        authorityDisplayLabel.setOpaque(true);

        numCarsLabel.setBackground(new java.awt.Color(153, 204, 255));
        numCarsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        numCarsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCarsLabel.setText("Number of Cars");
        numCarsLabel.setOpaque(true);

        powerDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        powerDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        powerDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        powerDisplayLabel.setOpaque(true);

        heightDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        heightDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        heightDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        heightDisplayLabel.setOpaque(true);

        lightsDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        lightsDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lightsDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lightsDisplayLabel.setOpaque(true);

        leftDoorDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        leftDoorDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        leftDoorDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftDoorDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        leftDoorDisplayLabel.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(213, 166, 189));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Current");
        jLabel1.setOpaque(true);

        trainIdLabel.setBackground(new java.awt.Color(153, 204, 255));
        trainIdLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        trainIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainIdLabel.setText("Train ID");
        trainIdLabel.setBorder(new javax.swing.border.MatteBorder(null));
        trainIdLabel.setOpaque(true);

        authorityLabel.setBackground(new java.awt.Color(153, 204, 255));
        authorityLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        authorityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorityLabel.setText("Authority");
        authorityLabel.setOpaque(true);

        powerLabel.setBackground(new java.awt.Color(153, 204, 255));
        powerLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        powerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerLabel.setText("Power");
        powerLabel.setOpaque(true);

        currentTrainSpeedLabel.setBackground(new java.awt.Color(153, 204, 255));
        currentTrainSpeedLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        currentTrainSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrainSpeedLabel.setText("Current Train Speed");
        currentTrainSpeedLabel.setOpaque(true);

        lightsLabel.setBackground(new java.awt.Color(153, 204, 255));
        lightsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightsLabel.setText("Lights");
        lightsLabel.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(213, 166, 189));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Doors");
        jLabel8.setOpaque(true);

        widthDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        widthDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        widthDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        widthDisplayLabel.setOpaque(true);

        lengthDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        lengthDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lengthDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lengthDisplayLabel.setOpaque(true);

        rightDoorDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        rightDoorDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rightDoorDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightDoorDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rightDoorDisplayLabel.setOpaque(true);

        numCarsDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        numCarsDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        numCarsDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCarsDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCarsDisplayLabel.setOpaque(true);

        crewDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        crewDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        crewDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crewDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        crewDisplayLabel.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(213, 166, 189));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Debug Mode");
        jLabel2.setOpaque(true);

        debugModeGroup.add(debugModeOnButton);
        debugModeOnButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        debugModeOnButton.setText("ON");
        debugModeOnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        debugModeGroup.add(debugModeOffButton);
        debugModeOffButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        debugModeOffButton.setText("OFF");
        debugModeOffButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debugModeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugModeOffButtonActionPerformed(evt);
            }
        });

        jLabel41.setBackground(new java.awt.Color(153, 204, 255));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Debug Mode");
        jLabel41.setOpaque(true);

        setAuthorityInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel43.setBackground(new java.awt.Color(153, 204, 255));
        jLabel43.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Lights");
        jLabel43.setOpaque(true);

        jLabel44.setBackground(new java.awt.Color(234, 153, 153));
        jLabel44.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Set Power(kW)");
        jLabel44.setOpaque(true);

        setPowerInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel45.setBackground(new java.awt.Color(213, 166, 189));
        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Doors");
        jLabel45.setOpaque(true);

        jLabel46.setBackground(new java.awt.Color(153, 204, 255));
        jLabel46.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Left");
        jLabel46.setOpaque(true);

        jLabel47.setBackground(new java.awt.Color(153, 204, 255));
        jLabel47.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Right");
        jLabel47.setOpaque(true);

        jLabel48.setBackground(new java.awt.Color(153, 204, 255));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Set Temperture (F)");
        jLabel48.setOpaque(true);

        setTemperatureInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel49.setBackground(new java.awt.Color(153, 204, 255));
        jLabel49.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Set Authority");
        jLabel49.setOpaque(true);

        jLabel50.setBackground(new java.awt.Color(67, 67, 67));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 0, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Failures");
        jLabel50.setOpaque(true);

        applyChangesButton.setBackground(new java.awt.Color(255, 229, 153));
        applyChangesButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        applyChangesButton.setText("APPLY CHANGES");
        applyChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangesButtonActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(213, 166, 189));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Message Board");
        jLabel13.setOpaque(true);

        messageBoardDisplayLabel.setBackground(new java.awt.Color(183, 183, 183));
        messageBoardDisplayLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        messageBoardDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageBoardDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        messageBoardDisplayLabel.setOpaque(true);

        brakeFailure.setBackground(new java.awt.Color(255, 0, 0));
        brakeFailure.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        brakeFailure.setText("Brake Failure");
        brakeFailure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brakeFailureActionPerformed(evt);
            }
        });

        engineFailure.setBackground(new java.awt.Color(255, 0, 0));
        engineFailure.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        engineFailure.setText("Engine Failure");
        engineFailure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineFailureActionPerformed(evt);
            }
        });

        signalFailure.setBackground(new java.awt.Color(255, 0, 0));
        signalFailure.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signalFailure.setText("Signal Failure");
        signalFailure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalFailureActionPerformed(evt);
            }
        });

        leftOpen.setBackground(new java.awt.Color(255, 229, 153));
        leftOpen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        leftOpen.setText("OPEN");
        leftOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftOpenActionPerformed(evt);
            }
        });

        leftClose.setBackground(new java.awt.Color(255, 229, 153));
        leftClose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        leftClose.setText("CLOSE");
        leftClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftCloseActionPerformed(evt);
            }
        });

        rightOpen.setBackground(new java.awt.Color(255, 229, 153));
        rightOpen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rightOpen.setText("OPEN");
        rightOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightOpenActionPerformed(evt);
            }
        });

        rightClose.setBackground(new java.awt.Color(255, 229, 153));
        rightClose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rightClose.setText("CLOSE");
        rightClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightCloseActionPerformed(evt);
            }
        });

        lightsOn.setBackground(new java.awt.Color(255, 229, 153));
        lightsOn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lightsOn.setText("ON");
        lightsOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsOnActionPerformed(evt);
            }
        });

        lightsOff.setBackground(new java.awt.Color(255, 229, 153));
        lightsOff.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lightsOff.setText("OFF");
        lightsOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsOffActionPerformed(evt);
            }
        });

        emergencyBrakeButton.setBackground(new java.awt.Color(255, 0, 0));
        emergencyBrakeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emergencyBrakeButton.setText("Emergency Brakes");
        emergencyBrakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyBrakeButtonActionPerformed(evt);
            }
        });

        suggestedSpeedLabel.setBackground(new java.awt.Color(153, 204, 255));
        suggestedSpeedLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        suggestedSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suggestedSpeedLabel.setText("Suggested Speed");
        suggestedSpeedLabel.setOpaque(true);

        suggestedSpeedDisplay.setBackground(new java.awt.Color(183, 183, 183));
        suggestedSpeedDisplay.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        suggestedSpeedDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suggestedSpeedDisplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        suggestedSpeedDisplay.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lightsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(lightsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(leftDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(leftDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rightDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(rightDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(passengersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(passengersDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(crewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(crewDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(emergencyBrakeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(emergencyBrakeDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(massLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(massDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(heightDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lengthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(widthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numCarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numCarsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(currentTrainSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(currentTrainSpeedDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(emergencyBrakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(powerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(7, 7, 7)
                                                    .addComponent(powerDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(accelerationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(trainIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(7, 7, 7)
                                                            .addComponent(trainIdPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(37, 37, 37))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(authorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(7, 7, 7)
                                                            .addComponent(authorityDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(39, 39, 39)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(suggestedSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(temperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(temperatureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(accelerationDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(suggestedSpeedDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageBoardDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                        .addComponent(setTemperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(setPowerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(setAuthorityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lightsOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lightsOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(leftOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(leftClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rightOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(rightClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(debugModeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(debugModeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(engineFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signalFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(applyChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brakeFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(trainIdPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(temperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(authorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(authorityDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(powerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(powerDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentTrainSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentTrainSpeedDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lightsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lightsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leftDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leftDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rightDoorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rightDoorDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passengersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passengersDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crewDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(suggestedSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(accelerationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(accelerationDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(suggestedSpeedDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(13, 13, 13)
                                .addComponent(emergencyBrakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emergencyBrakeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emergencyBrakeDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(massLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(massDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heightDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(widthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lengthDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numCarsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numCarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(brakeFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(engineFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signalFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(messageBoardDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(debugModeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(debugModeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setPowerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setTemperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setAuthorityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lightsOn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lightsOff, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leftOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leftClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rightOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void debugModeOffButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void applyChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            double pInput = Double.parseDouble(setPowerInput.getText());
            double powerInput = pInput*1000;
            myTrain.setPower(powerInput,1);
            double tInput = Double.parseDouble(setTemperatureInput.getText());
            myTrain.setTemperature(tInput);
        }
        else{
            double pInput = Double.parseDouble(setPowerInput.getText());
            double powerInput = pInput*1000;
            myTrain.setPower(powerInput,0);
        }

    }

    private void trainIdPickerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String s = trainIdPicker.getSelectedItem().toString();
        int id = Integer.parseInt(""+s.charAt(6));
        Train tempTrain = TrainTracker.getTrainTracker().getTrain(id);
        tempTrain.getGUI().setVisible(true);
    }

    boolean isFirstClick3 = true;
    private void brakeFailureActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(isFirstClick3)
        {
             myTrain.brakeFailureMode(true);
             isFirstClick3 = false;
        }
        else
        {
             myTrain.brakeFailureMode(false);
             isFirstClick3 = true;
        }
    }

    boolean isFirstClick1 = true;
    private void engineFailureActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(isFirstClick1)
        {
             myTrain.engineFailureMode(true);
             isFirstClick1 = false;
        }
        else
        {
             myTrain.engineFailureMode(false);
             isFirstClick1 = true;
        }
    }

    boolean isFirstClick2 = true;
    private void signalFailureActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(isFirstClick2)
        {
             myTrain.signalFailureMode(true);
             isFirstClick2 = false;
        }
        else
        {
             myTrain.signalFailureMode(false);
             isFirstClick2 = true;
        }
    }

    private void leftOpenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            myTrain.setLeftDoor(1);
        }
    }

    private void leftCloseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            myTrain.setLeftDoor(0);
        }
    }

    private void rightOpenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            myTrain.setRightDoor(1);
        }
    }

    private void rightCloseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            myTrain.setRightDoor(0);
        }
    }

    private void lightsOnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            myTrain.setLights(true);
        }
    }

    private void lightsOffActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(debugModeOnButton.isSelected()){
            myTrain.setLights(false);
        }
    }

    private boolean isFirstClick = true;
    private void emergencyBrakeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(isFirstClick)
        {
             myTrain.setEmergencyBrakes(true);
             isFirstClick = false;
        }
        else
        {
             myTrain.setEmergencyBrakes(false);
             isFirstClick = true;
        }
    }

    private void eBrakeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainModelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainModelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    protected javax.swing.JLabel accelerationDisplayLabel;
    protected javax.swing.JLabel accelerationLabel;
    protected javax.swing.JButton applyChangesButton;
    protected javax.swing.JLabel authorityDisplayLabel;
    protected javax.swing.JLabel authorityLabel;
    protected javax.swing.JButton brakeFailure;
    protected javax.swing.ButtonGroup brakesGroup;
    protected javax.swing.JLabel crewDisplayLabel;
    protected javax.swing.JLabel messageBoardDisplayLabel;
    protected javax.swing.JLabel crewLabel;
    protected javax.swing.JLabel currentTrainSpeedDisplayLabel;
    protected javax.swing.JLabel currentTrainSpeedLabel;
    protected javax.swing.ButtonGroup debugModeGroup;
    protected javax.swing.JRadioButton debugModeOffButton;
    protected javax.swing.JRadioButton debugModeOnButton;
    protected javax.swing.JButton emergencyBrakeButton;
    protected javax.swing.JLabel emergencyBrakeDisplayLabel;
    protected javax.swing.ButtonGroup emergencyBrakeGroup;
    protected javax.swing.JLabel emergencyBrakeLabel;
    protected javax.swing.JButton engineFailure;
    protected javax.swing.ButtonGroup engineGroup;
    protected javax.swing.JLabel heightDisplayLabel;
    protected javax.swing.JLabel heightLabel;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel13;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel30;
    protected javax.swing.JLabel jLabel41;
    protected javax.swing.JLabel jLabel43;
    protected javax.swing.JLabel jLabel44;
    protected javax.swing.JLabel jLabel45;
    protected javax.swing.JLabel jLabel46;
    protected javax.swing.JLabel jLabel47;
    protected javax.swing.JLabel jLabel48;
    protected javax.swing.JLabel jLabel49;
    protected javax.swing.JLabel jLabel50;
    protected javax.swing.JLabel jLabel8;
    protected javax.swing.JButton leftClose;
    protected javax.swing.JLabel leftDoorDisplayLabel;
    protected javax.swing.ButtonGroup leftDoorGroup;
    protected javax.swing.JLabel leftDoorLabel;
    protected javax.swing.JButton leftOpen;
    protected javax.swing.JLabel lengthDisplayLabel;
    protected javax.swing.JLabel lengthLabel;
    protected javax.swing.ButtonGroup lightGroup;
    protected javax.swing.JLabel lightsDisplayLabel;
    protected javax.swing.JLabel lightsLabel;
    protected javax.swing.JButton lightsOff;
    protected javax.swing.JButton lightsOn;
    protected javax.swing.JLabel massDisplayLabel;
    protected javax.swing.JLabel massLabel;
    protected javax.swing.JLabel numCarsDisplayLabel;
    protected javax.swing.JLabel numCarsLabel;
    protected javax.swing.JLabel passengersDisplayLabel;
    protected javax.swing.JLabel passengersLabel;
    protected javax.swing.JLabel powerDisplayLabel;
    protected javax.swing.JLabel powerLabel;
    protected javax.swing.JButton rightClose;
    protected javax.swing.JLabel rightDoorDisplayLabel;
    protected javax.swing.ButtonGroup rightDoorGroup;
    protected javax.swing.JLabel rightDoorLabel;
    protected javax.swing.JButton rightOpen;
    protected javax.swing.JTextField setAuthorityInput;
    protected javax.swing.JTextField setPowerInput;
    protected javax.swing.JTextField setTemperatureInput;
    protected javax.swing.JButton signalFailure;
    protected javax.swing.ButtonGroup signalGroup;
    protected javax.swing.JLabel suggestedSpeedDisplay;
    protected javax.swing.JLabel suggestedSpeedLabel;
    protected javax.swing.JLabel temperatureDisplayLabel;
    protected javax.swing.JLabel temperatureLabel;
    protected javax.swing.JLabel trainIdLabel;
    protected javax.swing.JComboBox<String> trainIdPicker;
    protected javax.swing.JLabel widthDisplayLabel;
    protected javax.swing.JLabel widthLabel;
    // End of variables declaration
}
